-- أحجام/متغيرات المنتج (مثل: صغير، وسط، كبير)
-- نفّذ في Supabase → SQL Editor

CREATE TABLE IF NOT EXISTS public.product_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  name text NOT NULL,
  price numeric NOT NULL CHECK (price >= 0),
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- إصلاح جدول قديم بأعمدة ناقصة أو مختلفة
ALTER TABLE public.product_variants
  ADD COLUMN IF NOT EXISTS name text,
  ADD COLUMN IF NOT EXISTS price numeric,
  ADD COLUMN IF NOT EXISTS sort_order int NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS product_variants_product_id_idx
  ON public.product_variants (product_id);

ALTER TABLE public.product_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "product_variants_public_read" ON public.product_variants;
DROP POLICY IF EXISTS "product_variants_anon_insert" ON public.product_variants;
DROP POLICY IF EXISTS "product_variants_anon_update" ON public.product_variants;
DROP POLICY IF EXISTS "product_variants_anon_delete" ON public.product_variants;

CREATE POLICY "product_variants_public_read"
ON public.product_variants FOR SELECT TO public USING (true);

CREATE POLICY "product_variants_anon_insert"
ON public.product_variants FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "product_variants_anon_update"
ON public.product_variants FOR UPDATE TO anon, authenticated
USING (true) WITH CHECK (true);

CREATE POLICY "product_variants_anon_delete"
ON public.product_variants FOR DELETE TO anon, authenticated USING (true);

-- بديل: jsonb على products (يُقرأ تلقائياً إن لم يوجد جدول product_variants)
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS variants jsonb DEFAULT '[]'::jsonb;

NOTIFY pgrst, 'reload schema';
